### PR TITLE
Feature/save user for experience posts

### PR DESCRIPTION
**Pull request by petterroea**

### CODE REVIEW

**Comment by AndreasJJ** [comment]
Does this still return the user's password and password hash?

**Comment by Letaguator** [comment]
Looking at the code again I believe you are correct in your assessment.

**Comment by Letaguator** [comment]
I have changed my review accordingly

**Comment by Letaguator** [comment]
@AndreasJJ approved it, and I am creating an issue regarding the sensitive data.

**Comment by AndreasJJ** [comment]
Swagger still shows that sensitive information is being sent. Idk if its not fixed or if swagger needs to be updated.
Skjermbilde 2020-02-22 kl  15 08 48

**Comment by petterroea** [comment]
Yes. This is the exact reason why #101 shouldn't exist. I fixed the wrong place because of lacking information.

**Pull request merged**
