### PR TITLE
Feature/multiple urls for metadata

### PR DESCRIPTION
**Pull request by Letaguator**

### CODE REVIEW

**Comment by Letaguator** [comment]
Btw, atm. er det ikke enforca at en released Metadata har minst en DataSource.

**Comment by Letaguator** [comment]
Should be ready for review.

**Comment by Letaguator** [comment]
Good point, I agree

**Comment by Letaguator** [comment]
Will change tomorrow

**Comment by AndreasJJ** [comment]
This is user story 20 right? let's follow the standard of making a story branch that the backend and frontend can merge into, debug and test before merging to development.

**Comment by Letaguator** [comment]
Yes, that is exactly what @MittBrukernavn pointed out :) And as I said, I agree.

**Pull request closed without merging**
